# -*- coding: utf-8 -*-
"""multi_variable_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhTeeecAWTxFLknjf9bdwhDggQVZg9B9
"""

import pandas as pd
data=pd.read_csv("Student_Performance.csv")

data.drop("Extracurricular Activities",axis=1,inplace=True)

import statsmodels.api as sm
y=data["Performance Index"]
x=data.drop("Performance Index",axis=1)
x=sm.add_constant(x)
sm_model=sm.OLS(endog=y,exog=x).fit()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
model =LinearRegression()
y =data['Performance Index']
X =data[['Hours Studied','Previous Scores']]
X_train,X_test,y_train,y_test  =train_test_split(X,y,test_size=0.25,random_state=1)
model.fit(X_train,y_train)
print(model.score(X_test,y_test))

import matplotlib.pyplot as plt
fig =plt.figure(figsize=(10,10))
sm.graphics.plot_partregress_grid(sm_model,fig=fig)

import seaborn as sns
sns.heatmap(data=data.corr(),annot=True)

sns.pairplot(data)

